import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import nftabis from "../abis/nft.json";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import {
  Carousel,
  CarouselContent,
  CarouselItem,
  CarouselNext,
  CarouselPrevious,
} from "@/components/ui/carousel";
import Image from "next/image";
import { useWriteContract, useWaitForTransactionReceipt } from "wagmi";
import { useEffect } from "react";
import { useToast } from "@/hooks/use-toast";

// 假设这是您的 NFT 合约 ABI 和地址
const NFT_CONTRACT_ABI = nftabis;
const NFT_CONTRACT_ADDRESS = "0xECa46674517649d9eEDD1BADe61e7ec25e3c42F0";

const MintNFT: React.FC = () => {
  const { toast } = useToast();

  const {
    data: hash,
    error: writeError,
    isPending,
    writeContractAsync,
  } = useWriteContract();

  const { isLoading: isConfirming, isSuccess: isConfirmed } =
    useWaitForTransactionReceipt({
      hash,
    });

  const handleMint = async () => {
    await writeContractAsync({
      abi: NFT_CONTRACT_ABI,
      address: NFT_CONTRACT_ADDRESS,
      functionName: "mintNFT",
    });
  };

  useEffect(() => {
    if (isConfirmed) {
      toast({
        title: "Success",
        description: "NFT minted successfully!",
      });
    }
  }, [isConfirmed, toast]);

  useEffect(() => {
    if (writeError) {
      toast({
        variant: "destructive",
        title: "Error",
        description: (writeError as Error)?.message || "An error occurred while minting",
      });
    }
  }, [writeError, toast]);

  return (
    <Card className="w-[350px]">
      <CardHeader>
        <CardTitle>Mint Your NFT</CardTitle>
        <CardDescription>Get your unique NFT now!</CardDescription>
      </CardHeader>
      <CardContent>
        <Carousel>
          <CarouselContent>
            {[1, 2, 3].map((id) => (
              <CarouselItem key={id}>
                <Image
                  src={`/nft/${id}.png`}
                  alt={`NFT Preview ${id}`}
                  width={300}
                  height={300}
                />
              </CarouselItem>
            ))}
          </CarouselContent>
          <CarouselPrevious />
          <CarouselNext />
        </Carousel>
      </CardContent>
      <CardFooter>
        <Button onClick={handleMint} disabled={isPending || isConfirming}>
          {isPending
            ? "Confirming..."
            : isConfirming
            ? "Minting..."
            : "Mint NFT"}
        </Button>
      </CardFooter>
      {hash && <div>Transaction Hash: {hash}</div>}
      {isConfirming && <div>Waiting for confirmation...</div>}
      {isConfirmed && <div>NFT minted successfully!</div>}
    </Card>
  );
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <header className={styles.header}>
        <div className={styles.logoTitle}>
          <h1 className={styles.title}>NFT Mint</h1>
        </div>
        <ConnectButton />
      </header>

      <main className={styles.main}>
        <MintNFT />
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
